// Generated by CoffeeScript 1.7.1
(function() {
  var TEST_REGEXP, allTestFiles, pathToModule;

  allTestFiles = [];

  TEST_REGEXP = /app\/assets\/javascripts\/\w*\/\w*\.spec\.\w*$/;

  pathToModule = function(path) {
    return path.replace(/^\/base\//, "../../").replace(/\.js$/, "");
  };

  Object.keys(window.__karma__.files).forEach(function(file) {
    if (TEST_REGEXP.test(file)) {
      allTestFiles.push(pathToModule(file));
    }
  });

  requirejs.config({
    baseUrl: "base/app/assets/javascripts",
    paths: {
      'angular': 'angular/angular',
      'angular-mocks': 'angular-mocks/angular-mocks',
      'angular-resource': 'angular-resource/angular-resource',
      'angular-animate': 'angular-animate/angular-animate',
      'angular-ui-router': 'angular-ui-router/release/angular-ui-router',
      'bindonce': 'angular-bindonce/bindonce',
      'ui-bootstrap-tpls': 'angular-bootstrap/ui-bootstrap-tpls',
      'jquery': 'jquery/dist/jquery',
      'lodash': 'lodash/dist/lodash',
      'bootstrap': 'sass-bootstrap/dist/js/bootstrap'
    },
    shim: {
      'angular': {
        exports: 'angular',
        deps: ['jquery']
      },
      'angular-mocks': ['angular'],
      'lodash': {
        exports: '_'
      },
      'angular-resource': ['angular'],
      'angular-animate': ['angular'],
      'angular-ui-router': ['angular'],
      'bindonce': ['angular'],
      'ui-bootstrap-tpls': ['angular'],
      'bootstrap': ['jquery']
    },
    deps: allTestFiles,
    callback: window.__karma__.start
  });

}).call(this);
